pipeline {
    agent any
    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/jfrog/project-examples.git"
            }
        }

        stage ('Artifactory configuration') {
            steps {
                rtServer (
                    id: "my-jfrog-registry",
                    url: "http://localhost:8081/artifactory",
                    credentialsId: "jfrog-cred"
                )

                rtMavenDeployer (
                    id: "MAVEN_DEPLOYER",
                    serverId: "my-jfrog-registry",
                    releaseRepo: "example-repo-local",
                    snapshotRepo: "example-repo-local"
                )

                rtMavenResolver (
                    id: "MAVEN_RESOLVER",
                    serverId: "my-jfrog-registry",
                    releaseRepo: "example-repo-local",
                    snapshotRepo: "example-repo-local"
                )
            }
        }

        stage ('Exec Maven') {
            steps {
                rtMavenRun (
                    tool: "M3", // Tool name from Jenkins configuration
                    pom: 'maven-examples/maven-example/pom.xml',
                    goals: 'clean install'
                )
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "my-jfrog-registry"
                )
            }
        }
    }
}
